# Generated by Django 5.0.4 on 2024-04-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.IntegerField()),
                ('lesson_title', models.CharField(max_length=100)),
                ('lesson_description', models.TextField()),
                ('user', models.TextField()),
            ],
            options={
                'db_table': 'LEARNING_INFO',
            },
        ),
    ]
